version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=kulturaview
      - DB_PASSWORD=secure_password_123
      - DB_NAME=kulturaview
      - JWT_SECRET=your_super_secure_jwt_secret_key_here_make_it_very_long
      - PORT=5000
    depends_on:
      - db
    volumes:
      - uploads:/app/uploads
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_password_123
      - MYSQL_DATABASE=kulturaview
      - MYSQL_USER=kulturaview
      - MYSQL_PASSWORD=secure_password_123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  mysql_data:
  uploads:
